language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

sudo: false

before_script:
  # Update Composer
  - composer self-update

  # Install Nette Tester
  - composer install --no-interaction --prefer-source

  # Coveralls
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini >> ./tests/php-unix.ini; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then NTESTER_FLAGS="--coverage ./coverage.xml --coverage-src ./src"; else TESTER_FLAGS=""; fi

  # PHPSTAN
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" && "$COMPOSER_FLAG" == "" ]]; then PHPSTAN=1; fi

script:
  - vendor/bin/tester tests/cases -p php -i
  - vendor/bin/tester tests/cases -s -p php -c tests/php-unix.ini $NTESTER_FLAGS

  # PHPSTAN
  - if [ "$PHPSTAN" != "" ]; then composer require phpstan/phpstan:^0.6.4; fi
  - if [ "$PHPSTAN" != "" ]; then vendor/bin/phpstan analyze --level 5 src tests; fi

after_script:
    # Coveralls
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require satooshi/php-coveralls; fi
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php vendor/bin/coveralls -c tests/.coveralls.yml -v; fi

after_failure:
    # Print *.actual content
    - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
